server:
  port: 9092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!
  data:
    mongodb:
      host: 34.136.114.18
      port: 27777
      database: BilgeadamMicroservices
      username: bilgeuser #superadmin ->AdminBilge
      password: bilge!!** #superadmin ->"m=YEJ-Sw_2oF6lp8uPr5"
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    #    url: jdbc:postgresql://34.132.121.83:5062/java3user
#    url: jdbc:postgresql://localhost:5432/BilgeadamMicroservicesUserService
#    username: postgres
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

# REDIS
myredis:
  host: localhost
  port: 6379

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}

myapplication:
  user-service:
    feign-client: http://localhost:9092/api/v1
  elastic-service:
    feign-client: http://localhost:9099/api/v1/elastic