server:
  port: 9092

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://34.132.121.83:5062/java3user
    url: jdbc:postgresql://localhost:5432/BilgeadamMicroservicesUserService
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# REDIS
myredis:
  host: localhost
  port: 6379

# JWT
myjwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}